dev-dependencies = { }

[dependencies]
base = "0.13.6"
stableheapbtreemap = "1.5.0"
star = "0.1.1"
map = "9.0.1"
vector = "0.4.0"
candy = "0.3.0"
icrc1-mo = "0.0.15"
ovs-fixed = "0.1.2"
candy-utils = "0.7.0"
timer-tool = "0.1.0"
ic-certification = "0.1.3"
icrc10-mo = "0.0.1"
base16 = "1.0.0"
account = "1.0.1"
account-identifier = "1.0.2"
"icrc75.mo" = "https://github.com/icdevsorg/icrc75.mo#classplus@1d52e80332417fa7824c5ed7917788fd3c80cd87"
icrc72-subscriber-mo = "0.0.1"

[package]
name = "mvevent"
version = "0.0.1"
description = "manage subscriptions for icrc72"
repository = "https://github.com/PanIndustrial-Org/mvevent"
keywords = [ "pubsub" ]
